FROM centos-7-with-git:0.0.1
RUN mkdir /app
ADD server /app/server
ADD worker /app/worker
COPY frontend /app/frontend
COPY script /app/script
COPY sql /app/sql
COPY start_server.sh /app
COPY start_worker.sh /app
RUN yum update -y && yum install -y subversion git curl git-svn
RUN git config --global user.name osc-admin
RUN git config --global user.email osc-admin@oschina.cn
WORKDIR /app
ENTRYPOINT ["/bin/bash", "-c"]
CMD ["./start_worker.sh"]
