// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"ctgb/models"
)

// CreateCCHistoryCreatedCode is the HTTP code returned for type CreateCCHistoryCreated
const CreateCCHistoryCreatedCode int = 201

/*CreateCCHistoryCreated cc历史信息

swagger:response createCCHistoryCreated
*/
type CreateCCHistoryCreated struct {

	/*
	  In: Body
	*/
	Payload *models.OK `json:"body,omitempty"`
}

// NewCreateCCHistoryCreated creates CreateCCHistoryCreated with default headers values
func NewCreateCCHistoryCreated() *CreateCCHistoryCreated {

	return &CreateCCHistoryCreated{}
}

// WithPayload adds the payload to the create c c history created response
func (o *CreateCCHistoryCreated) WithPayload(payload *models.OK) *CreateCCHistoryCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create c c history created response
func (o *CreateCCHistoryCreated) SetPayload(payload *models.OK) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateCCHistoryCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateCCHistoryInternalServerErrorCode is the HTTP code returned for type CreateCCHistoryInternalServerError
const CreateCCHistoryInternalServerErrorCode int = 500

/*CreateCCHistoryInternalServerError 内部错误

swagger:response createCCHistoryInternalServerError
*/
type CreateCCHistoryInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorModel `json:"body,omitempty"`
}

// NewCreateCCHistoryInternalServerError creates CreateCCHistoryInternalServerError with default headers values
func NewCreateCCHistoryInternalServerError() *CreateCCHistoryInternalServerError {

	return &CreateCCHistoryInternalServerError{}
}

// WithPayload adds the payload to the create c c history internal server error response
func (o *CreateCCHistoryInternalServerError) WithPayload(payload *models.ErrorModel) *CreateCCHistoryInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create c c history internal server error response
func (o *CreateCCHistoryInternalServerError) SetPayload(payload *models.ErrorModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateCCHistoryInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
