// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateCCHistoryHandlerFunc turns a function with the right signature into a create c c history handler
type CreateCCHistoryHandlerFunc func(CreateCCHistoryParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateCCHistoryHandlerFunc) Handle(params CreateCCHistoryParams) middleware.Responder {
	return fn(params)
}

// CreateCCHistoryHandler interface for that can handle valid create c c history params
type CreateCCHistoryHandler interface {
	Handle(CreateCCHistoryParams) middleware.Responder
}

// NewCreateCCHistory creates a new http.Handler for the create c c history operation
func NewCreateCCHistory(ctx *middleware.Context, handler CreateCCHistoryHandler) *CreateCCHistory {
	return &CreateCCHistory{Context: ctx, Handler: handler}
}

/* CreateCCHistory swagger:route POST /cc_history createCCHistory

cc历史信息

*/
type CreateCCHistory struct {
	Context *middleware.Context
	Handler CreateCCHistoryHandler
}

func (o *CreateCCHistory) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateCCHistoryParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
