// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"ctgb/models"
)

// CreatePlanCreatedCode is the HTTP code returned for type CreatePlanCreated
const CreatePlanCreatedCode int = 201

/*CreatePlanCreated 成功

swagger:response createPlanCreated
*/
type CreatePlanCreated struct {

	/*
	  In: Body
	*/
	Payload *models.OK `json:"body,omitempty"`
}

// NewCreatePlanCreated creates CreatePlanCreated with default headers values
func NewCreatePlanCreated() *CreatePlanCreated {

	return &CreatePlanCreated{}
}

// WithPayload adds the payload to the create plan created response
func (o *CreatePlanCreated) WithPayload(payload *models.OK) *CreatePlanCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create plan created response
func (o *CreatePlanCreated) SetPayload(payload *models.OK) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreatePlanCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreatePlanInternalServerErrorCode is the HTTP code returned for type CreatePlanInternalServerError
const CreatePlanInternalServerErrorCode int = 500

/*CreatePlanInternalServerError 内部错误

swagger:response createPlanInternalServerError
*/
type CreatePlanInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorModel `json:"body,omitempty"`
}

// NewCreatePlanInternalServerError creates CreatePlanInternalServerError with default headers values
func NewCreatePlanInternalServerError() *CreatePlanInternalServerError {

	return &CreatePlanInternalServerError{}
}

// WithPayload adds the payload to the create plan internal server error response
func (o *CreatePlanInternalServerError) WithPayload(payload *models.ErrorModel) *CreatePlanInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create plan internal server error response
func (o *CreatePlanInternalServerError) SetPayload(payload *models.ErrorModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreatePlanInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
