// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"ctgb/models"
)

// CreateScheduleCreatedCode is the HTTP code returned for type CreateScheduleCreated
const CreateScheduleCreatedCode int = 201

/*CreateScheduleCreated 成功

swagger:response createScheduleCreated
*/
type CreateScheduleCreated struct {

	/*
	  In: Body
	*/
	Payload *models.OK `json:"body,omitempty"`
}

// NewCreateScheduleCreated creates CreateScheduleCreated with default headers values
func NewCreateScheduleCreated() *CreateScheduleCreated {

	return &CreateScheduleCreated{}
}

// WithPayload adds the payload to the create schedule created response
func (o *CreateScheduleCreated) WithPayload(payload *models.OK) *CreateScheduleCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create schedule created response
func (o *CreateScheduleCreated) SetPayload(payload *models.OK) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateScheduleCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateScheduleInternalServerErrorCode is the HTTP code returned for type CreateScheduleInternalServerError
const CreateScheduleInternalServerErrorCode int = 500

/*CreateScheduleInternalServerError 内部错误

swagger:response createScheduleInternalServerError
*/
type CreateScheduleInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorModel `json:"body,omitempty"`
}

// NewCreateScheduleInternalServerError creates CreateScheduleInternalServerError with default headers values
func NewCreateScheduleInternalServerError() *CreateScheduleInternalServerError {

	return &CreateScheduleInternalServerError{}
}

// WithPayload adds the payload to the create schedule internal server error response
func (o *CreateScheduleInternalServerError) WithPayload(payload *models.ErrorModel) *CreateScheduleInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create schedule internal server error response
func (o *CreateScheduleInternalServerError) SetPayload(payload *models.ErrorModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateScheduleInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
