// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"

	"ctgb/models"
)

// NewCreateCCHistoryParams creates a new CreateCCHistoryParams object
//
// There are no default values defined in the spec.
func NewCreateCCHistoryParams() CreateCCHistoryParams {

	return CreateCCHistoryParams{}
}

// CreateCCHistoryParams contains all the bound params for the create c c history operation
// typically these are obtained from a http.Request
//
// swagger:parameters CreateCCHistory
type CreateCCHistoryParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: header
	*/
	AuthToken string
	/*
	  In: query
	*/
	Action *string
	/*
	  In: query
	*/
	GitName *string
	/*
	  In: body
	*/
	InfoItem *models.CCHistoryInfoModelItem
	/*
	  In: query
	*/
	OldGitName *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewCreateCCHistoryParams() beforehand.
func (o *CreateCCHistoryParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	if err := o.bindAuthToken(r.Header[http.CanonicalHeaderKey("AuthToken")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	qAction, qhkAction, _ := qs.GetOK("action")
	if err := o.bindAction(qAction, qhkAction, route.Formats); err != nil {
		res = append(res, err)
	}

	qGitName, qhkGitName, _ := qs.GetOK("git_name")
	if err := o.bindGitName(qGitName, qhkGitName, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.CCHistoryInfoModelItem
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("infoItem", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(context.Background())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.InfoItem = &body
			}
		}
	}

	qOldGitName, qhkOldGitName, _ := qs.GetOK("old_git_name")
	if err := o.bindOldGitName(qOldGitName, qhkOldGitName, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindAuthToken binds and validates parameter AuthToken from header.
func (o *CreateCCHistoryParams) bindAuthToken(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("AuthToken", "header", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("AuthToken", "header", raw); err != nil {
		return err
	}
	o.AuthToken = raw

	return nil
}

// bindAction binds and validates parameter Action from query.
func (o *CreateCCHistoryParams) bindAction(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.Action = &raw

	return nil
}

// bindGitName binds and validates parameter GitName from query.
func (o *CreateCCHistoryParams) bindGitName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.GitName = &raw

	return nil
}

// bindOldGitName binds and validates parameter OldGitName from query.
func (o *CreateCCHistoryParams) bindOldGitName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.OldGitName = &raw

	return nil
}
