// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"ctgb/models"
)

// DeleteTaskCacheOKCode is the HTTP code returned for type DeleteTaskCacheOK
const DeleteTaskCacheOKCode int = 200

/*DeleteTaskCacheOK 成功

swagger:response deleteTaskCacheOK
*/
type DeleteTaskCacheOK struct {

	/*
	  In: Body
	*/
	Payload *models.OK `json:"body,omitempty"`
}

// NewDeleteTaskCacheOK creates DeleteTaskCacheOK with default headers values
func NewDeleteTaskCacheOK() *DeleteTaskCacheOK {

	return &DeleteTaskCacheOK{}
}

// WithPayload adds the payload to the delete task cache o k response
func (o *DeleteTaskCacheOK) WithPayload(payload *models.OK) *DeleteTaskCacheOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete task cache o k response
func (o *DeleteTaskCacheOK) SetPayload(payload *models.OK) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteTaskCacheOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteTaskCacheInternalServerErrorCode is the HTTP code returned for type DeleteTaskCacheInternalServerError
const DeleteTaskCacheInternalServerErrorCode int = 500

/*DeleteTaskCacheInternalServerError 内部错误

swagger:response deleteTaskCacheInternalServerError
*/
type DeleteTaskCacheInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorModel `json:"body,omitempty"`
}

// NewDeleteTaskCacheInternalServerError creates DeleteTaskCacheInternalServerError with default headers values
func NewDeleteTaskCacheInternalServerError() *DeleteTaskCacheInternalServerError {

	return &DeleteTaskCacheInternalServerError{}
}

// WithPayload adds the payload to the delete task cache internal server error response
func (o *DeleteTaskCacheInternalServerError) WithPayload(payload *models.ErrorModel) *DeleteTaskCacheInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete task cache internal server error response
func (o *DeleteTaskCacheInternalServerError) SetPayload(payload *models.ErrorModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteTaskCacheInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
