// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetFrontConfigHandlerFunc turns a function with the right signature into a get front config handler
type GetFrontConfigHandlerFunc func(GetFrontConfigParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetFrontConfigHandlerFunc) Handle(params GetFrontConfigParams) middleware.Responder {
	return fn(params)
}

// GetFrontConfigHandler interface for that can handle valid get front config params
type GetFrontConfigHandler interface {
	Handle(GetFrontConfigParams) middleware.Responder
}

// NewGetFrontConfig creates a new http.Handler for the get front config operation
func NewGetFrontConfig(ctx *middleware.Context, handler GetFrontConfigHandler) *GetFrontConfig {
	return &GetFrontConfig{Context: ctx, Handler: handler}
}

/* GetFrontConfig swagger:route GET /frontend_configs getFrontConfig

前端配置

*/
type GetFrontConfig struct {
	Context *middleware.Context
	Handler GetFrontConfigHandler
}

func (o *GetFrontConfig) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetFrontConfigParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
