// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"ctgb/models"
)

// GetTaskOKCode is the HTTP code returned for type GetTaskOK
const GetTaskOKCode int = 200

/*GetTaskOK 任务信息

swagger:response getTaskOK
*/
type GetTaskOK struct {

	/*
	  In: Body
	*/
	Payload *models.TaskDetail `json:"body,omitempty"`
}

// NewGetTaskOK creates GetTaskOK with default headers values
func NewGetTaskOK() *GetTaskOK {

	return &GetTaskOK{}
}

// WithPayload adds the payload to the get task o k response
func (o *GetTaskOK) WithPayload(payload *models.TaskDetail) *GetTaskOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get task o k response
func (o *GetTaskOK) SetPayload(payload *models.TaskDetail) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTaskOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetTaskInternalServerErrorCode is the HTTP code returned for type GetTaskInternalServerError
const GetTaskInternalServerErrorCode int = 500

/*GetTaskInternalServerError 内部错误

swagger:response getTaskInternalServerError
*/
type GetTaskInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorModel `json:"body,omitempty"`
}

// NewGetTaskInternalServerError creates GetTaskInternalServerError with default headers values
func NewGetTaskInternalServerError() *GetTaskInternalServerError {

	return &GetTaskInternalServerError{}
}

// WithPayload adds the payload to the get task internal server error response
func (o *GetTaskInternalServerError) WithPayload(payload *models.ErrorModel) *GetTaskInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get task internal server error response
func (o *GetTaskInternalServerError) SetPayload(payload *models.ErrorModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTaskInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
