// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetWorkerHandlerFunc turns a function with the right signature into a get worker handler
type GetWorkerHandlerFunc func(GetWorkerParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetWorkerHandlerFunc) Handle(params GetWorkerParams) middleware.Responder {
	return fn(params)
}

// GetWorkerHandler interface for that can handle valid get worker params
type GetWorkerHandler interface {
	Handle(GetWorkerParams) middleware.Responder
}

// NewGetWorker creates a new http.Handler for the get worker operation
func NewGetWorker(ctx *middleware.Context, handler GetWorkerHandler) *GetWorker {
	return &GetWorker{Context: ctx, Handler: handler}
}

/* GetWorker swagger:route GET /workers/{id} getWorker

工作节点详情

*/
type GetWorker struct {
	Context *middleware.Context
	Handler GetWorkerHandler
}

func (o *GetWorker) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetWorkerParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
