// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListTaskHandlerFunc turns a function with the right signature into a list task handler
type ListTaskHandlerFunc func(ListTaskParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListTaskHandlerFunc) Handle(params ListTaskParams) middleware.Responder {
	return fn(params)
}

// ListTaskHandler interface for that can handle valid list task params
type ListTaskHandler interface {
	Handle(ListTaskParams) middleware.Responder
}

// NewListTask creates a new http.Handler for the list task operation
func NewListTask(ctx *middleware.Context, handler ListTaskHandler) *ListTask {
	return &ListTask{Context: ctx, Handler: handler}
}

/* ListTask swagger:route GET /tasks listTask

任务列表

*/
type ListTask struct {
	Context *middleware.Context
	Handler ListTaskHandler
}

func (o *ListTask) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewListTaskParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
