// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListLogsHandlerFunc turns a function with the right signature into a list logs handler
type ListLogsHandlerFunc func(ListLogsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListLogsHandlerFunc) Handle(params ListLogsParams) middleware.Responder {
	return fn(params)
}

// ListLogsHandler interface for that can handle valid list logs params
type ListLogsHandler interface {
	Handle(ListLogsParams) middleware.Responder
}

// NewListLogs creates a new http.Handler for the list logs operation
func NewListLogs(ctx *middleware.Context, handler ListLogsHandler) *ListLogs {
	return &ListLogs{Context: ctx, Handler: handler}
}

/* ListLogs swagger:route POST /logs listLogs

获取日志

*/
type ListLogs struct {
	Context *middleware.Context
	Handler ListLogsHandler
}

func (o *ListLogs) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewListLogsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
