// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewListPvobComponentStreamParams creates a new ListPvobComponentStreamParams object
//
// There are no default values defined in the spec.
func NewListPvobComponentStreamParams() ListPvobComponentStreamParams {

	return ListPvobComponentStreamParams{}
}

// ListPvobComponentStreamParams contains all the bound params for the list pvob component stream operation
// typically these are obtained from a http.Request
//
// swagger:parameters ListPvobComponentStream
type ListPvobComponentStreamParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	ComponentID string
	/*
	  Required: true
	  In: path
	*/
	PvobID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewListPvobComponentStreamParams() beforehand.
func (o *ListPvobComponentStreamParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rComponentID, rhkComponentID, _ := route.Params.GetOK("component_id")
	if err := o.bindComponentID(rComponentID, rhkComponentID, route.Formats); err != nil {
		res = append(res, err)
	}

	rPvobID, rhkPvobID, _ := route.Params.GetOK("pvob_id")
	if err := o.bindPvobID(rPvobID, rhkPvobID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindComponentID binds and validates parameter ComponentID from path.
func (o *ListPvobComponentStreamParams) bindComponentID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.ComponentID = raw

	return nil
}

// bindPvobID binds and validates parameter PvobID from path.
func (o *ListPvobComponentStreamParams) bindPvobID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.PvobID = raw

	return nil
}
