// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewListSvnUsernameParams creates a new ListSvnUsernameParams object
//
// There are no default values defined in the spec.
func NewListSvnUsernameParams() ListSvnUsernameParams {

	return ListSvnUsernameParams{}
}

// ListSvnUsernameParams contains all the bound params for the list svn username operation
// typically these are obtained from a http.Request
//
// swagger:parameters ListSvnUsername
type ListSvnUsernameParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: query
	*/
	SvnPassword string
	/*
	  Required: true
	  In: query
	*/
	SvnURL string
	/*
	  Required: true
	  In: query
	*/
	SvnUser string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewListSvnUsernameParams() beforehand.
func (o *ListSvnUsernameParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qSvnPassword, qhkSvnPassword, _ := qs.GetOK("svn_password")
	if err := o.bindSvnPassword(qSvnPassword, qhkSvnPassword, route.Formats); err != nil {
		res = append(res, err)
	}

	qSvnURL, qhkSvnURL, _ := qs.GetOK("svn_url")
	if err := o.bindSvnURL(qSvnURL, qhkSvnURL, route.Formats); err != nil {
		res = append(res, err)
	}

	qSvnUser, qhkSvnUser, _ := qs.GetOK("svn_user")
	if err := o.bindSvnUser(qSvnUser, qhkSvnUser, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindSvnPassword binds and validates parameter SvnPassword from query.
func (o *ListSvnUsernameParams) bindSvnPassword(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("svn_password", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("svn_password", "query", raw); err != nil {
		return err
	}
	o.SvnPassword = raw

	return nil
}

// bindSvnURL binds and validates parameter SvnURL from query.
func (o *ListSvnUsernameParams) bindSvnURL(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("svn_url", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("svn_url", "query", raw); err != nil {
		return err
	}
	o.SvnURL = raw

	return nil
}

// bindSvnUser binds and validates parameter SvnUser from query.
func (o *ListSvnUsernameParams) bindSvnUser(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("svn_user", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("svn_user", "query", raw); err != nil {
		return err
	}
	o.SvnUser = raw

	return nil
}
