// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListPvobHandlerFunc turns a function with the right signature into a list pvob handler
type ListPvobHandlerFunc func(ListPvobParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListPvobHandlerFunc) Handle(params ListPvobParams) middleware.Responder {
	return fn(params)
}

// ListPvobHandler interface for that can handle valid list pvob params
type ListPvobHandler interface {
	Handle(ListPvobParams) middleware.Responder
}

// NewListPvob creates a new http.Handler for the list pvob operation
func NewListPvob(ctx *middleware.Context, handler ListPvobHandler) *ListPvob {
	return &ListPvob{Context: ctx, Handler: handler}
}

/* ListPvob swagger:route GET /pvobs listPvob

pvob列表

*/
type ListPvob struct {
	Context *middleware.Context
	Handler ListPvobHandler
}

func (o *ListPvob) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewListPvobParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
