// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"ctgb/models"
)

// ListSvnUsernameOKCode is the HTTP code returned for type ListSvnUsernameOK
const ListSvnUsernameOKCode int = 200

/*ListSvnUsernameOK 用户名列表

swagger:response listSvnUsernameOK
*/
type ListSvnUsernameOK struct {

	/*
	  In: Body
	*/
	Payload []string `json:"body,omitempty"`
}

// NewListSvnUsernameOK creates ListSvnUsernameOK with default headers values
func NewListSvnUsernameOK() *ListSvnUsernameOK {

	return &ListSvnUsernameOK{}
}

// WithPayload adds the payload to the list svn username o k response
func (o *ListSvnUsernameOK) WithPayload(payload []string) *ListSvnUsernameOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list svn username o k response
func (o *ListSvnUsernameOK) SetPayload(payload []string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListSvnUsernameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]string, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ListSvnUsernameInternalServerErrorCode is the HTTP code returned for type ListSvnUsernameInternalServerError
const ListSvnUsernameInternalServerErrorCode int = 500

/*ListSvnUsernameInternalServerError 内部错误

swagger:response listSvnUsernameInternalServerError
*/
type ListSvnUsernameInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorModel `json:"body,omitempty"`
}

// NewListSvnUsernameInternalServerError creates ListSvnUsernameInternalServerError with default headers values
func NewListSvnUsernameInternalServerError() *ListSvnUsernameInternalServerError {

	return &ListSvnUsernameInternalServerError{}
}

// WithPayload adds the payload to the list svn username internal server error response
func (o *ListSvnUsernameInternalServerError) WithPayload(payload *models.ErrorModel) *ListSvnUsernameInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list svn username internal server error response
func (o *ListSvnUsernameInternalServerError) SetPayload(payload *models.ErrorModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListSvnUsernameInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
