// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListScheduleHandlerFunc turns a function with the right signature into a list schedule handler
type ListScheduleHandlerFunc func(ListScheduleParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListScheduleHandlerFunc) Handle(params ListScheduleParams) middleware.Responder {
	return fn(params)
}

// ListScheduleHandler interface for that can handle valid list schedule params
type ListScheduleHandler interface {
	Handle(ListScheduleParams) middleware.Responder
}

// NewListSchedule creates a new http.Handler for the list schedule operation
func NewListSchedule(ctx *middleware.Context, handler ListScheduleHandler) *ListSchedule {
	return &ListSchedule{Context: ctx, Handler: handler}
}

/* ListSchedule swagger:route GET /schedules listSchedule

定时任务列表

*/
type ListSchedule struct {
	Context *middleware.Context
	Handler ListScheduleHandler
}

func (o *ListSchedule) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewListScheduleParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
