// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListPvobComponentStreamHandlerFunc turns a function with the right signature into a list pvob component stream handler
type ListPvobComponentStreamHandlerFunc func(ListPvobComponentStreamParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListPvobComponentStreamHandlerFunc) Handle(params ListPvobComponentStreamParams) middleware.Responder {
	return fn(params)
}

// ListPvobComponentStreamHandler interface for that can handle valid list pvob component stream params
type ListPvobComponentStreamHandler interface {
	Handle(ListPvobComponentStreamParams) middleware.Responder
}

// NewListPvobComponentStream creates a new http.Handler for the list pvob component stream operation
func NewListPvobComponentStream(ctx *middleware.Context, handler ListPvobComponentStreamHandler) *ListPvobComponentStream {
	return &ListPvobComponentStream{Context: ctx, Handler: handler}
}

/* ListPvobComponentStream swagger:route GET /pvobs/{pvob_id}/components/{component_id} listPvobComponentStream

流列表

*/
type ListPvobComponentStream struct {
	Context *middleware.Context
	Handler ListPvobComponentStreamHandler
}

func (o *ListPvobComponentStream) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewListPvobComponentStreamParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
