// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"ctgb/models"
)

// ListUserOKCode is the HTTP code returned for type ListUserOK
const ListUserOKCode int = 200

/*ListUserOK 账户列表

swagger:response listUserOK
*/
type ListUserOK struct {

	/*
	  In: Body
	*/
	Payload []*models.UserPageInfoModel `json:"body,omitempty"`
}

// NewListUserOK creates ListUserOK with default headers values
func NewListUserOK() *ListUserOK {

	return &ListUserOK{}
}

// WithPayload adds the payload to the list user o k response
func (o *ListUserOK) WithPayload(payload []*models.UserPageInfoModel) *ListUserOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list user o k response
func (o *ListUserOK) SetPayload(payload []*models.UserPageInfoModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListUserOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.UserPageInfoModel, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ListUserInternalServerErrorCode is the HTTP code returned for type ListUserInternalServerError
const ListUserInternalServerErrorCode int = 500

/*ListUserInternalServerError 内部错误

swagger:response listUserInternalServerError
*/
type ListUserInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorModel `json:"body,omitempty"`
}

// NewListUserInternalServerError creates ListUserInternalServerError with default headers values
func NewListUserInternalServerError() *ListUserInternalServerError {

	return &ListUserInternalServerError{}
}

// WithPayload adds the payload to the list user internal server error response
func (o *ListUserInternalServerError) WithPayload(payload *models.ErrorModel) *ListUserInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list user internal server error response
func (o *ListUserInternalServerError) SetPayload(payload *models.ErrorModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListUserInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
