// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"
)

// ListPvobComponentStreamURL generates an URL for the list pvob component stream operation
type ListPvobComponentStreamURL struct {
	ComponentID string
	PvobID      string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *ListPvobComponentStreamURL) WithBasePath(bp string) *ListPvobComponentStreamURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *ListPvobComponentStreamURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *ListPvobComponentStreamURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/pvobs/{pvob_id}/components/{component_id}"

	componentID := o.ComponentID
	if componentID != "" {
		_path = strings.Replace(_path, "{component_id}", componentID, -1)
	} else {
		return nil, errors.New("componentId is required on ListPvobComponentStreamURL")
	}

	pvobID := o.PvobID
	if pvobID != "" {
		_path = strings.Replace(_path, "{pvob_id}", pvobID, -1)
	} else {
		return nil, errors.New("pvobId is required on ListPvobComponentStreamURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *ListPvobComponentStreamURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *ListPvobComponentStreamURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *ListPvobComponentStreamURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on ListPvobComponentStreamURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on ListPvobComponentStreamURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *ListPvobComponentStreamURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
