// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"

	"github.com/go-openapi/swag"
)

// ListPlanURL generates an URL for the list plan operation
type ListPlanURL struct {
	Group      *string
	Limit      int64
	Offset     int64
	OriginType *string
	Status     *string
	Supporter  *string
	Team       *string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *ListPlanURL) WithBasePath(bp string) *ListPlanURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *ListPlanURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *ListPlanURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/plans"

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var groupQ string
	if o.Group != nil {
		groupQ = *o.Group
	}
	if groupQ != "" {
		qs.Set("group", groupQ)
	}

	limitQ := swag.FormatInt64(o.Limit)
	if limitQ != "" {
		qs.Set("limit", limitQ)
	}

	offsetQ := swag.FormatInt64(o.Offset)
	if offsetQ != "" {
		qs.Set("offset", offsetQ)
	}

	var originTypeQ string
	if o.OriginType != nil {
		originTypeQ = *o.OriginType
	}
	if originTypeQ != "" {
		qs.Set("originType", originTypeQ)
	}

	var statusQ string
	if o.Status != nil {
		statusQ = *o.Status
	}
	if statusQ != "" {
		qs.Set("status", statusQ)
	}

	var supporterQ string
	if o.Supporter != nil {
		supporterQ = *o.Supporter
	}
	if supporterQ != "" {
		qs.Set("supporter", supporterQ)
	}

	var teamQ string
	if o.Team != nil {
		teamQ = *o.Team
	}
	if teamQ != "" {
		qs.Set("team", teamQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *ListPlanURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *ListPlanURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *ListPlanURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on ListPlanURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on ListPlanURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *ListPlanURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
