// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	"ctgb/models"
)

// NewPingWorkerParams creates a new PingWorkerParams object
//
// There are no default values defined in the spec.
func NewPingWorkerParams() PingWorkerParams {

	return PingWorkerParams{}
}

// PingWorkerParams contains all the bound params for the ping worker operation
// typically these are obtained from a http.Request
//
// swagger:parameters PingWorker
type PingWorkerParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*worker信息
	  Required: true
	  In: body
	*/
	WorkerInfo *models.WorkerModel
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPingWorkerParams() beforehand.
func (o *PingWorkerParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.WorkerModel
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("workerInfo", "body", ""))
			} else {
				res = append(res, errors.NewParseError("workerInfo", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(context.Background())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.WorkerInfo = &body
			}
		}
	} else {
		res = append(res, errors.Required("workerInfo", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
