// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"ctgb/models"
)

// SearchCCHistoryOKCode is the HTTP code returned for type SearchCCHistoryOK
const SearchCCHistoryOKCode int = 200

/*SearchCCHistoryOK cc历史ID

swagger:response searchCCHistoryOK
*/
type SearchCCHistoryOK struct {

	/*
	  In: Body
	*/
	Payload []string `json:"body,omitempty"`
}

// NewSearchCCHistoryOK creates SearchCCHistoryOK with default headers values
func NewSearchCCHistoryOK() *SearchCCHistoryOK {

	return &SearchCCHistoryOK{}
}

// WithPayload adds the payload to the search c c history o k response
func (o *SearchCCHistoryOK) WithPayload(payload []string) *SearchCCHistoryOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the search c c history o k response
func (o *SearchCCHistoryOK) SetPayload(payload []string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SearchCCHistoryOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]string, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// SearchCCHistoryInternalServerErrorCode is the HTTP code returned for type SearchCCHistoryInternalServerError
const SearchCCHistoryInternalServerErrorCode int = 500

/*SearchCCHistoryInternalServerError 内部错误

swagger:response searchCCHistoryInternalServerError
*/
type SearchCCHistoryInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorModel `json:"body,omitempty"`
}

// NewSearchCCHistoryInternalServerError creates SearchCCHistoryInternalServerError with default headers values
func NewSearchCCHistoryInternalServerError() *SearchCCHistoryInternalServerError {

	return &SearchCCHistoryInternalServerError{}
}

// WithPayload adds the payload to the search c c history internal server error response
func (o *SearchCCHistoryInternalServerError) WithPayload(payload *models.ErrorModel) *SearchCCHistoryInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the search c c history internal server error response
func (o *SearchCCHistoryInternalServerError) SetPayload(payload *models.ErrorModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SearchCCHistoryInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
