// Code generated by go-swagger; DO NOT EDIT.

// Package restapi CC To Git Service
//
//  Terms Of Service:
//    http://swagger.io/terms/
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 1.0.0
//  License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
//  Contact: <apiteam@swagger.io>
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
