// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "translator",
    "termsOfService": "http://swagger.io/terms/",
    "contact": {
      "email": "apiteam@swagger.io"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.0"
  },
  "basePath": "/gitee-cc",
  "paths": {
    "/cc_history": {
      "get": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "cc历史信息",
        "operationId": "GetCCHistory",
        "parameters": [
          {
            "type": "integer",
            "default": 0,
            "name": "limit",
            "in": "query",
            "required": true
          },
          {
            "type": "integer",
            "default": 0,
            "name": "offset",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "git_name",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "id",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "cc历史信息",
            "schema": {
              "$ref": "#/definitions/CCHistoryInfoModel"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        }
      },
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "cc历史信息",
        "operationId": "CreateCCHistory",
        "parameters": [
          {
            "type": "string",
            "name": "git_name",
            "in": "query"
          },
          {
            "type": "string",
            "name": "action",
            "in": "query"
          },
          {
            "name": "infoItem",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/CCHistoryInfoModelItem"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "cc历史信息",
            "schema": {
              "$ref": "#/definitions/OK"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "CCHistoryInfoModel": {
      "type": "object",
      "properties": {
        "count": {
          "type": "integer"
        },
        "infoItem": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/CCHistoryInfoModelItem"
          }
        },
        "limit": {
          "type": "integer"
        },
        "offset": {
          "type": "integer"
        }
      }
    },
    "CCHistoryInfoModelItem": {
      "type": "object",
      "properties": {
        "createTime": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "historyType": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "owner": {
          "type": "string"
        }
      }
    },
    "ErrorModel": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "example": 400
        },
        "message": {
          "type": "string",
          "example": "error message"
        }
      }
    },
    "OK": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "translator",
    "termsOfService": "http://swagger.io/terms/",
    "contact": {
      "email": "apiteam@swagger.io"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.0"
  },
  "basePath": "/gitee-cc",
  "paths": {
    "/cc_history": {
      "get": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "cc历史信息",
        "operationId": "GetCCHistory",
        "parameters": [
          {
            "type": "integer",
            "default": 0,
            "name": "limit",
            "in": "query",
            "required": true
          },
          {
            "type": "integer",
            "default": 0,
            "name": "offset",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "git_name",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "id",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "cc历史信息",
            "schema": {
              "$ref": "#/definitions/CCHistoryInfoModel"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        }
      },
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "cc历史信息",
        "operationId": "CreateCCHistory",
        "parameters": [
          {
            "type": "string",
            "name": "git_name",
            "in": "query"
          },
          {
            "type": "string",
            "name": "action",
            "in": "query"
          },
          {
            "name": "infoItem",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/CCHistoryInfoModelItem"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "cc历史信息",
            "schema": {
              "$ref": "#/definitions/OK"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "CCHistoryInfoModel": {
      "type": "object",
      "properties": {
        "count": {
          "type": "integer"
        },
        "infoItem": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/CCHistoryInfoModelItem"
          }
        },
        "limit": {
          "type": "integer"
        },
        "offset": {
          "type": "integer"
        }
      }
    },
    "CCHistoryInfoModelItem": {
      "type": "object",
      "properties": {
        "createTime": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "historyType": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "owner": {
          "type": "string"
        }
      }
    },
    "ErrorModel": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "example": 400
        },
        "message": {
          "type": "string",
          "example": "error message"
        }
      }
    },
    "OK": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        }
      }
    }
  }
}`))
}
