swagger: "2.0"
schemes:
  - http
info:
  version: "1.0.0"
  title: "translator"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
basePath: "/gitee-cc"
paths:
  /cc_history:
    get:
      summary: cc历史信息
      description: ''
      operationId: GetCCHistory
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: limit
          in: query
          required: true
          default: 0
          type: integer
        - name: offset
          in: query
          required: true
          default: 0
          type: integer
        - name: git_name
          in: query
          required: true
          type: string
        - name: id
          in: query
          type: string
      responses:
        '200':
          description: cc历史信息
          schema:
            $ref: '#/definitions/CCHistoryInfoModel'
        '500':
          description: 内部错误
          schema:
            $ref: '#/definitions/ErrorModel'
    post:
      summary: cc历史信息
      description: ''
      operationId: CreateCCHistory
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: git_name
          in: query
          type: string
        - name: action
          in: query
          type: string
        - name: infoItem
          in: body
          schema:
            $ref: '#/definitions/CCHistoryInfoModelItem'
      responses:
        '201':
          description: cc历史信息
          schema:
            $ref: '#/definitions/OK'
        '500':
          description: 内部错误
          schema:
            $ref: '#/definitions/ErrorModel'
definitions:
  ErrorModel:
    type: object
    properties:
      message:
        type: string
        example: error message
      code:
        type: integer
        example: 400
  CCHistoryInfoModelItem:
    type: object
    properties:
      name:
        type: string
      owner:
        type: string
      createTime:
        type: string
      id:
        type: string
      historyType:
        type: string
      description:
        type: string
  CCHistoryInfoModel:
    type: object
    properties:
      limit:
        type: integer
      offset:
        type: integer
      count:
        type: integer
      infoItem:
        type: array
        items:
          $ref: '#/definitions/CCHistoryInfoModelItem'
  OK:
    type: object
    properties:
      message:
        type: string