// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CCHistoryInfoModelItem c c history info model item
//
// swagger:model CCHistoryInfoModelItem
type CCHistoryInfoModelItem struct {

	// create time
	CreateTime string `json:"createTime,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// history type
	HistoryType string `json:"historyType,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// owner
	Owner string `json:"owner,omitempty"`
}

// Validate validates this c c history info model item
func (m *CCHistoryInfoModelItem) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this c c history info model item based on context it is used
func (m *CCHistoryInfoModelItem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CCHistoryInfoModelItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CCHistoryInfoModelItem) UnmarshalBinary(b []byte) error {
	var res CCHistoryInfoModelItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
