// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// HistoryIDList history ID list
//
// swagger:model HistoryIDList
type HistoryIDList []string

// Validate validates this history ID list
func (m HistoryIDList) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this history ID list based on context it is used
func (m HistoryIDList) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
