// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LogPageInfoModel log page info model
//
// swagger:model LogPageInfoModel
type LogPageInfoModel struct {

	// count
	Count int64 `json:"count,omitempty"`

	// limit
	Limit int64 `json:"limit,omitempty"`

	// log info
	LogInfo []*LogInfoModel `json:"logInfo"`

	// offset
	Offset int64 `json:"offset,omitempty"`
}

// Validate validates this log page info model
func (m *LogPageInfoModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLogInfo(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LogPageInfoModel) validateLogInfo(formats strfmt.Registry) error {
	if swag.IsZero(m.LogInfo) { // not required
		return nil
	}

	for i := 0; i < len(m.LogInfo); i++ {
		if swag.IsZero(m.LogInfo[i]) { // not required
			continue
		}

		if m.LogInfo[i] != nil {
			if err := m.LogInfo[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("logInfo" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this log page info model based on the context it is used
func (m *LogPageInfoModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateLogInfo(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LogPageInfoModel) contextValidateLogInfo(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.LogInfo); i++ {

		if m.LogInfo[i] != nil {
			if err := m.LogInfo[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("logInfo" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *LogPageInfoModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LogPageInfoModel) UnmarshalBinary(b []byte) error {
	var res LogPageInfoModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
