// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LogFilterParamsModel log filter params model
//
// swagger:model LogFilterParamsModel
type LogFilterParamsModel struct {

	// action
	Action string `json:"action,omitempty"`

	// level
	Level string `json:"level,omitempty"`

	// limit
	Limit int64 `json:"limit,omitempty"`

	// offset
	Offset int64 `json:"offset,omitempty"`

	// user
	User string `json:"user,omitempty"`
}

// Validate validates this log filter params model
func (m *LogFilterParamsModel) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this log filter params model based on context it is used
func (m *LogFilterParamsModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LogFilterParamsModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LogFilterParamsModel) UnmarshalBinary(b []byte) error {
	var res LogFilterParamsModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
