// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PlanPageInfoModel plan page info model
//
// swagger:model PlanPageInfoModel
type PlanPageInfoModel struct {

	// count
	Count int64 `json:"count,omitempty"`

	// limit
	Limit int64 `json:"limit,omitempty"`

	// offset
	Offset int64 `json:"offset,omitempty"`

	// plan info
	PlanInfo []*PlanModel `json:"planInfo"`
}

// Validate validates this plan page info model
func (m *PlanPageInfoModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePlanInfo(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PlanPageInfoModel) validatePlanInfo(formats strfmt.Registry) error {
	if swag.IsZero(m.PlanInfo) { // not required
		return nil
	}

	for i := 0; i < len(m.PlanInfo); i++ {
		if swag.IsZero(m.PlanInfo[i]) { // not required
			continue
		}

		if m.PlanInfo[i] != nil {
			if err := m.PlanInfo[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("planInfo" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this plan page info model based on the context it is used
func (m *PlanPageInfoModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePlanInfo(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PlanPageInfoModel) contextValidatePlanInfo(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.PlanInfo); i++ {

		if m.PlanInfo[i] != nil {
			if err := m.PlanInfo[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("planInfo" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *PlanPageInfoModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PlanPageInfoModel) UnmarshalBinary(b []byte) error {
	var res PlanPageInfoModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
