// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SchedulePageInfoModel schedule page info model
//
// swagger:model SchedulePageInfoModel
type SchedulePageInfoModel struct {

	// count
	Count int64 `json:"count,omitempty"`

	// limit
	Limit int64 `json:"limit,omitempty"`

	// offset
	Offset int64 `json:"offset,omitempty"`

	// task info
	TaskInfo []*ScheduleModel `json:"taskInfo"`
}

// Validate validates this schedule page info model
func (m *SchedulePageInfoModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTaskInfo(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SchedulePageInfoModel) validateTaskInfo(formats strfmt.Registry) error {
	if swag.IsZero(m.TaskInfo) { // not required
		return nil
	}

	for i := 0; i < len(m.TaskInfo); i++ {
		if swag.IsZero(m.TaskInfo[i]) { // not required
			continue
		}

		if m.TaskInfo[i] != nil {
			if err := m.TaskInfo[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("taskInfo" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this schedule page info model based on the context it is used
func (m *SchedulePageInfoModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateTaskInfo(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SchedulePageInfoModel) contextValidateTaskInfo(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.TaskInfo); i++ {

		if m.TaskInfo[i] != nil {
			if err := m.TaskInfo[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("taskInfo" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *SchedulePageInfoModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SchedulePageInfoModel) UnmarshalBinary(b []byte) error {
	var res SchedulePageInfoModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
