// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ScheduleModel schedule model
//
// swagger:model ScheduleModel
type ScheduleModel struct {

	// id
	ID int64 `json:"id,omitempty"`

	// schedule
	Schedule string `json:"schedule,omitempty"`

	// status
	Status string `json:"status,omitempty"`

	// task id
	TaskID int64 `json:"task_id,omitempty"`
}

// Validate validates this schedule model
func (m *ScheduleModel) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this schedule model based on context it is used
func (m *ScheduleModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ScheduleModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ScheduleModel) UnmarshalBinary(b []byte) error {
	var res ScheduleModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
