// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TaskCommandOut task command out
//
// swagger:model TaskCommandOut
type TaskCommandOut struct {

	// content
	Content string `json:"content,omitempty"`

	// log id
	LogID int64 `json:"log_id,omitempty"`
}

// Validate validates this task command out
func (m *TaskCommandOut) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this task command out based on context it is used
func (m *TaskCommandOut) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TaskCommandOut) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TaskCommandOut) UnmarshalBinary(b []byte) error {
	var res TaskCommandOut
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
