// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TaskLogInfo task log info
//
// swagger:model TaskLogInfo
type TaskLogInfo struct {

	// duration
	Duration string `json:"duration,omitempty"`

	// end time
	EndTime string `json:"endTime,omitempty" db:"end_time"`

	// log ID
	LogID string `json:"logID,omitempty" db:"log_id"`

	// start time
	StartTime string `json:"startTime,omitempty" db:"start_time"`

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this task log info
func (m *TaskLogInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this task log info based on context it is used
func (m *TaskLogInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TaskLogInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TaskLogInfo) UnmarshalBinary(b []byte) error {
	var res TaskLogInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
