// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TaskDetail task detail
//
// swagger:model TaskDetail
type TaskDetail struct {

	// log list
	LogList []*TaskLogInfo `json:"logList"`

	// task model
	TaskModel *TaskModel `json:"taskModel,omitempty"`
}

// Validate validates this task detail
func (m *TaskDetail) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLogList(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTaskModel(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TaskDetail) validateLogList(formats strfmt.Registry) error {
	if swag.IsZero(m.LogList) { // not required
		return nil
	}

	for i := 0; i < len(m.LogList); i++ {
		if swag.IsZero(m.LogList[i]) { // not required
			continue
		}

		if m.LogList[i] != nil {
			if err := m.LogList[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("logList" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *TaskDetail) validateTaskModel(formats strfmt.Registry) error {
	if swag.IsZero(m.TaskModel) { // not required
		return nil
	}

	if m.TaskModel != nil {
		if err := m.TaskModel.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("taskModel")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this task detail based on the context it is used
func (m *TaskDetail) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateLogList(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTaskModel(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TaskDetail) contextValidateLogList(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.LogList); i++ {

		if m.LogList[i] != nil {
			if err := m.LogList[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("logList" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *TaskDetail) contextValidateTaskModel(ctx context.Context, formats strfmt.Registry) error {

	if m.TaskModel != nil {
		if err := m.TaskModel.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("taskModel")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TaskDetail) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TaskDetail) UnmarshalBinary(b []byte) error {
	var res TaskDetail
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
