// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TaskMatchInfo task match info
//
// swagger:model TaskMatchInfo
type TaskMatchInfo struct {

	// git branch
	GitBranch JsonNullString `json:"gitBranch,omitempty" db:"git_branch"`

	// stream
	Stream JsonNullString `json:"stream,omitempty"`
}

// Validate validates this task match info
func (m *TaskMatchInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this task match info based on context it is used
func (m *TaskMatchInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TaskMatchInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TaskMatchInfo) UnmarshalBinary(b []byte) error {
	var res TaskMatchInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
