// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UserInfoModel user info model
//
// swagger:model UserInfoModel
type UserInfoModel struct {

	// password
	Password string `json:"password,omitempty"`

	// user ID
	UserID int64 `json:"userID,omitempty"`

	// user name
	UserName string `json:"userName,omitempty"`
}

// Validate validates this user info model
func (m *UserInfoModel) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this user info model based on context it is used
func (m *UserInfoModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserInfoModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserInfoModel) UnmarshalBinary(b []byte) error {
	var res UserInfoModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
