// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// WorkerModel worker model
//
// swagger:model WorkerModel
type WorkerModel struct {

	// host
	// Example: 192.168.1.1
	Host string `json:"host,omitempty"`

	// port
	// Example: 80
	Port int64 `json:"port,omitempty"`
}

// Validate validates this worker model
func (m *WorkerModel) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this worker model based on context it is used
func (m *WorkerModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WorkerModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WorkerModel) UnmarshalBinary(b []byte) error {
	var res WorkerModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
