// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// WorkerPageInfoModel worker page info model
//
// swagger:model WorkerPageInfoModel
type WorkerPageInfoModel struct {

	// count
	Count int64 `json:"count,omitempty"`

	// worker info
	WorkerInfo []*WorkerDetail `json:"workerInfo"`
}

// Validate validates this worker page info model
func (m *WorkerPageInfoModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateWorkerInfo(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WorkerPageInfoModel) validateWorkerInfo(formats strfmt.Registry) error {
	if swag.IsZero(m.WorkerInfo) { // not required
		return nil
	}

	for i := 0; i < len(m.WorkerInfo); i++ {
		if swag.IsZero(m.WorkerInfo[i]) { // not required
			continue
		}

		if m.WorkerInfo[i] != nil {
			if err := m.WorkerInfo[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("workerInfo" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this worker page info model based on the context it is used
func (m *WorkerPageInfoModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateWorkerInfo(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WorkerPageInfoModel) contextValidateWorkerInfo(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.WorkerInfo); i++ {

		if m.WorkerInfo[i] != nil {
			if err := m.WorkerInfo[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("workerInfo" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *WorkerPageInfoModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WorkerPageInfoModel) UnmarshalBinary(b []byte) error {
	var res WorkerPageInfoModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
